#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
        n= 0
        count = []
          sortedarr = []
          for i in range(len(arr)):
              if arr[i] > n:
                  n = arr[i]
          for i in range(n):
            count.append(0)
          for i in arr:
            count[i] +=1
          for i in range(len(count)-1):
             count[i+1] = count[i+1] + count[i]
          for i in range(len(count)-1,0,-1):
              count[i] = count[i-1]
          count[0]= 0
          for i in range(len(arr)):
             sortedarr.append(0)
          for i in arr:
              sortedarr[count[i]] = i
              count[i] +=1
          return sortedarr

      
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
