#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    stack = []
    vm= []
    summ = 0
    numvaly = 0
    for i in range(len(path)):
        if path[i] == 'D':
            stack.append(-1)
        else: 
            stack.append(1)
    for i in range(len(stack)):
        summ += stack[i]
        vm.append(summ)
    for i in range(len(vm)):
        if vm[i] ==0 and vm[i-1]<0:
            numvaly+=1
    return numvaly
        
            
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
