#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
        Integer_array = []
        for grades in grades:
            if (grades%10== 0) or (grades < 38):
                Integer_array.append(grades)
            elif grades%10 <= 5:
                NextMultipleOFFive = grades + (5- grades%10)
                if NextMultipleOFFive - grades < 3:
                    Integer_array.append(NextMultipleOFFive)
                else:
                    Integer_array.append(grades)
            elif grades%10>5:
                NextMultipleOFFive=grades + (10-grades%10)
                if NextMultipleOFFive - grades < 3:
                    Integer_array.append(NextMultipleOFFive)
                else:
                   Integer_array.append(grades)
        return Integer_array


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
