#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    x = arr[n-1]
    for i in range(n,1,-1):
        if x < arr[i-2]:
            arr[i-1] = arr[i-2]
            for i in arr:
                print(f"{i}",end=" ")
            print("\r")
        elif x >= arr[i-2]:
            arr[i-1] = x
            for i in arr:
                print(f"{i}",end=" ")
            print("\r")
            break     
    if x<arr[0]:
        arr[0]= x
        for i in arr:
            print(f"{i}",end=" ")
            
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
